#!/bin/bash
git add . #tiek pieteiktas adreses "uzmanīšanai"
git config --global user.name SuccEgg
git config --global user.email rrudolfs@inbox.lv
#git commit -m "Class_05"
git commit -m "Class_$1"
git push origin main
